#pragma once

#include <cstdint>

namespace JE {

struct KeyModifiers
{
  bool Ctrl;
  bool Shift;
  bool Alt;
  bool Super;
};


namespace detail {

  static constexpr auto SCANCODE_MASK = 1U << 30U;
  constexpr auto ScanCodeToKeyCode(uint32_t scanCode) { return scanCode | SCANCODE_MASK; }

  enum ScanCode {
    UNKNOWN = 0,

    CAPSLOCK = 57,

    F1 = 58,
    F2 = 59,
    F3 = 60,
    F4 = 61,
    F5 = 62,
    F6 = 63,
    F7 = 64,
    F8 = 65,
    F9 = 66,
    F10 = 67,
    F11 = 68,
    F12 = 69,

    PRINTSCREEN = 70,
    SCROLLLOCK = 71,
    PAUSE = 72,
    INSERT = 73, /**< insert on PC, help on some Mac keyboards (but
                                   does send code 73, not 117) */
    HOME = 74,
    PAGEUP = 75,
    DELETE = 76,
    END = 77,
    PAGEDOWN = 78,
    RIGHT = 79,
    LEFT = 80,
    DOWN = 81,
    UP = 82,

    NUMLOCKCLEAR = 83, /**< num lock on PC, clear on Mac keyboards
                        */
    KP_DIVIDE = 84,
    KP_MULTIPLY = 85,
    KP_MINUS = 86,
    KP_PLUS = 87,
    KP_ENTER = 88,
    KP_1 = 89,
    KP_2 = 90,
    KP_3 = 91,
    KP_4 = 92,
    KP_5 = 93,
    KP_6 = 94,
    KP_7 = 95,
    KP_8 = 96,
    KP_9 = 97,
    KP_0 = 98,
    KP_PERIOD = 99,
    APPLICATION = 101, /**< windows contextual menu, compose */
    POWER = 102, /**< The USB document says this is a status flag,
                  *   not a physical key - but some Mac keyboards
                  *   do have a power key. */
    KP_EQUALS = 103,
    F13 = 104,
    F14 = 105,
    F15 = 106,
    F16 = 107,
    F17 = 108,
    F18 = 109,
    F19 = 110,
    F20 = 111,
    F21 = 112,
    F22 = 113,
    F23 = 114,
    F24 = 115,
    EXECUTE = 116,
    HELP = 117,
    MENU = 118,
    SELECT = 119,
    STOP = 120,
    AGAIN = 121, /**< redo */
    UNDO = 122,
    CUT = 123,
    COPY = 124,
    PASTE = 125,
    FIND = 126,
    MUTE = 127,
    VOLUMEUP = 128,
    VOLUMEDOWN = 129,
    KP_COMMA = 133,
    KP_EQUALSAS400 = 134,

    ALTERASE = 153, /**< Erase-Eaze */
    SYSREQ = 154,
    CANCEL = 155,
    CLEAR = 156,
    PRIOR = 157,
    RETURN2 = 158,
    SEPARATOR = 159,
    OUT = 160,
    OPER = 161,
    CLEARAGAIN = 162,
    CRSEL = 163,
    EXSEL = 164,

    KP_00 = 176,
    KP_000 = 177,
    THOUSANDSSEPARATOR = 178,
    DECIMALSEPARATOR = 179,
    CURRENCYUNIT = 180,
    CURRENCYSUBUNIT = 181,
    KP_LEFTPAREN = 182,
    KP_RIGHTPAREN = 183,
    KP_LEFTBRACE = 184,
    KP_RIGHTBRACE = 185,
    KP_TAB = 186,
    KP_BACKSPACE = 187,
    KP_A = 188,
    KP_B = 189,
    KP_C = 190,
    KP_D = 191,
    KP_E = 192,
    KP_F = 193,
    KP_XOR = 194,
    KP_POWER = 195,
    KP_PERCENT = 196,
    KP_LESS = 197,
    KP_GREATER = 198,
    KP_AMPERSAND = 199,
    KP_DBLAMPERSAND = 200,
    KP_VERTICALBAR = 201,
    KP_DBLVERTICALBAR = 202,
    KP_COLON = 203,
    KP_HASH = 204,
    KP_SPACE = 205,
    KP_AT = 206,
    KP_EXCLAM = 207,
    KP_MEMSTORE = 208,
    KP_MEMRECALL = 209,
    KP_MEMCLEAR = 210,
    KP_MEMADD = 211,
    KP_MEMSUBTRACT = 212,
    KP_MEMMULTIPLY = 213,
    KP_MEMDIVIDE = 214,
    KP_PLUSMINUS = 215,
    KP_CLEAR = 216,
    KP_CLEARENTRY = 217,
    KP_BINARY = 218,
    KP_OCTAL = 219,
    KP_DECIMAL = 220,
    KP_HEXADECIMAL = 221,

    LCTRL = 224,
    LSHIFT = 225,
    LALT = 226, /**< alt, option */
    LSuper = 227, /**< windows, command (apple), meta */
    RCTRL = 228,
    RSHIFT = 229,
    RALT = 230, /**< alt gr, option */
    RSuper = 231, /**< windows, command (apple), meta */

    MODE = 257, /**< I'm not sure if this is really not covered
                 *   by any of the above, but since there's a
                 *   special KMOD_MODE for it I'm adding it here
                 */

    AUDIONEXT = 258,
    AUDIOPREV = 259,
    AUDIOSTOP = 260,
    AUDIOPLAY = 261,
    AUDIOMUTE = 262,
    MEDIASELECT = 263,
    WWW = 264,
    MAIL = 265,
    CALCULATOR = 266,
    COMPUTER = 267,
    AC_SEARCH = 268,
    AC_HOME = 269,
    AC_BACK = 270,
    AC_FORWARD = 271,
    AC_STOP = 272,
    AC_REFRESH = 273,
    AC_BOOKMARKS = 274,
    BRIGHTNESSDOWN = 275,
    BRIGHTNESSUP = 276,
    DISPLAYSWITCH = 277, /**< display mirroring/dual display
                                           switch, video mode switch */
    KBDILLUMTOGGLE = 278,
    KBDILLUMDOWN = 279,
    KBDILLUMUP = 280,
    EJECT = 281,
    SLEEP = 282,

    APP1 = 283,
    APP2 = 284,

    AUDIOREWIND = 285,
    AUDIOFASTFORWARD = 286,

    SDL_NUM_SCANCODES = 512 /**< not a key, just marks the number of scancodes
                                 for array bounds */
  };
}// namespace detail


enum class KeyCode {
  Unknown = 0,

  Return = '\r',
  Escape = '\x1B',
  Backspace = '\b',
  Tab = '\t',
  Space = ' ',
  Exclaim = '!',
  QuotedBL = '"',
  Hash = '#',
  Percent = '%',
  Dollar = '$',
  Ampersand = '&',
  Quote = '\'',
  Leftparen = '(',
  Rightparen = ')',
  Asterisk = '*',
  Plus = '+',
  Comma = ',',
  Minus = '-',
  Period = '.',
  Slash = '/',
  Zero = '0',
  One = '1',
  Two = '2',
  Three = '3',
  Four = '4',
  Five = '5',
  Six = '6',
  Seven = '7',
  Eight = '8',
  Nine = '9',
  Colon = ':',
  Semicolon = ';',
  Less = '<',
  Equals = '=',
  Greater = '>',
  Question = '?',
  At = '@',

  /*
     Skip uppercase letters
   */

  Leftbracket = '[',
  Backslash = '\\',
  Rightbracket = ']',
  Caret = '^',
  Underscore = '_',
  Backquote = '`',
  a = 'a',
  b = 'b',
  c = 'c',
  d = 'd',
  e = 'e',
  f = 'f',
  g = 'g',
  h = 'h',
  i = 'i',
  j = 'j',
  k = 'k',
  l = 'l',
  m = 'm',
  n = 'n',
  o = 'o',
  p = 'p',
  q = 'q',
  r = 'r',
  s = 's',
  t = 't',
  u = 'u',
  v = 'v',
  w = 'w',
  x = 'x',
  y = 'y',
  z = 'z',

  Capslock = detail::ScanCodeToKeyCode(detail::ScanCode::CAPSLOCK),

  F1 = detail::ScanCodeToKeyCode(detail::ScanCode::F1),
  F2 = detail::ScanCodeToKeyCode(detail::ScanCode::F2),
  F3 = detail::ScanCodeToKeyCode(detail::ScanCode::F3),
  F4 = detail::ScanCodeToKeyCode(detail::ScanCode::F4),
  F5 = detail::ScanCodeToKeyCode(detail::ScanCode::F5),
  F6 = detail::ScanCodeToKeyCode(detail::ScanCode::F6),
  F7 = detail::ScanCodeToKeyCode(detail::ScanCode::F7),
  F8 = detail::ScanCodeToKeyCode(detail::ScanCode::F8),
  F9 = detail::ScanCodeToKeyCode(detail::ScanCode::F9),
  F10 = detail::ScanCodeToKeyCode(detail::ScanCode::F10),
  F11 = detail::ScanCodeToKeyCode(detail::ScanCode::F11),
  F12 = detail::ScanCodeToKeyCode(detail::ScanCode::F12),

  PrintScreen = detail::ScanCodeToKeyCode(detail::ScanCode::PRINTSCREEN),
  ScrollLock = detail::ScanCodeToKeyCode(detail::ScanCode::SCROLLLOCK),
  Pause = detail::ScanCodeToKeyCode(detail::ScanCode::PAUSE),
  Insert = detail::ScanCodeToKeyCode(detail::ScanCode::INSERT),
  Home = detail::ScanCodeToKeyCode(detail::ScanCode::HOME),
  PageUp = detail::ScanCodeToKeyCode(detail::ScanCode::PAGEUP),
  Delete = '\x7F',
  End = detail::ScanCodeToKeyCode(detail::ScanCode::END),
  PageDown = detail::ScanCodeToKeyCode(detail::ScanCode::PAGEDOWN),
  Right = detail::ScanCodeToKeyCode(detail::ScanCode::RIGHT),
  Left = detail::ScanCodeToKeyCode(detail::ScanCode::LEFT),
  Down = detail::ScanCodeToKeyCode(detail::ScanCode::DOWN),
  Up = detail::ScanCodeToKeyCode(detail::ScanCode::UP),

  NumLockClear = detail::ScanCodeToKeyCode(detail::ScanCode::NUMLOCKCLEAR),
  KeyPadDivide = detail::ScanCodeToKeyCode(detail::ScanCode::KP_DIVIDE),
  KeyPadMultiply = detail::ScanCodeToKeyCode(detail::ScanCode::KP_MULTIPLY),
  KeyPadMinus = detail::ScanCodeToKeyCode(detail::ScanCode::KP_MINUS),
  KeyPadPlus = detail::ScanCodeToKeyCode(detail::ScanCode::KP_PLUS),
  KeyPadEnter = detail::ScanCodeToKeyCode(detail::ScanCode::KP_ENTER),
  KeyPad1 = detail::ScanCodeToKeyCode(detail::ScanCode::KP_1),
  KeyPad2 = detail::ScanCodeToKeyCode(detail::ScanCode::KP_2),
  KeyPad3 = detail::ScanCodeToKeyCode(detail::ScanCode::KP_3),
  KeyPad4 = detail::ScanCodeToKeyCode(detail::ScanCode::KP_4),
  KeyPad5 = detail::ScanCodeToKeyCode(detail::ScanCode::KP_5),
  KeyPad6 = detail::ScanCodeToKeyCode(detail::ScanCode::KP_6),
  KeyPad7 = detail::ScanCodeToKeyCode(detail::ScanCode::KP_7),
  KeyPad8 = detail::ScanCodeToKeyCode(detail::ScanCode::KP_8),
  KeyPad9 = detail::ScanCodeToKeyCode(detail::ScanCode::KP_9),
  KeyPad0 = detail::ScanCodeToKeyCode(detail::ScanCode::KP_0),
  KeyPadPeriod = detail::ScanCodeToKeyCode(detail::ScanCode::KP_PERIOD),

  Application = detail::ScanCodeToKeyCode(detail::ScanCode::APPLICATION),
  Power = detail::ScanCodeToKeyCode(detail::ScanCode::POWER),
  KeyPadEquals = detail::ScanCodeToKeyCode(detail::ScanCode::KP_EQUALS),
  F13 = detail::ScanCodeToKeyCode(detail::ScanCode::F13),
  F14 = detail::ScanCodeToKeyCode(detail::ScanCode::F14),
  F15 = detail::ScanCodeToKeyCode(detail::ScanCode::F15),
  F16 = detail::ScanCodeToKeyCode(detail::ScanCode::F16),
  F17 = detail::ScanCodeToKeyCode(detail::ScanCode::F17),
  F18 = detail::ScanCodeToKeyCode(detail::ScanCode::F18),
  F19 = detail::ScanCodeToKeyCode(detail::ScanCode::F19),
  F20 = detail::ScanCodeToKeyCode(detail::ScanCode::F20),
  F21 = detail::ScanCodeToKeyCode(detail::ScanCode::F21),
  F22 = detail::ScanCodeToKeyCode(detail::ScanCode::F22),
  F23 = detail::ScanCodeToKeyCode(detail::ScanCode::F23),
  F24 = detail::ScanCodeToKeyCode(detail::ScanCode::F24),
  Execute = detail::ScanCodeToKeyCode(detail::ScanCode::EXECUTE),
  Help = detail::ScanCodeToKeyCode(detail::ScanCode::HELP),
  Menu = detail::ScanCodeToKeyCode(detail::ScanCode::MENU),
  Select = detail::ScanCodeToKeyCode(detail::ScanCode::SELECT),
  Stop = detail::ScanCodeToKeyCode(detail::ScanCode::STOP),
  Again = detail::ScanCodeToKeyCode(detail::ScanCode::AGAIN),
  Undo = detail::ScanCodeToKeyCode(detail::ScanCode::UNDO),
  Cut = detail::ScanCodeToKeyCode(detail::ScanCode::CUT),
  Copy = detail::ScanCodeToKeyCode(detail::ScanCode::COPY),
  Paste = detail::ScanCodeToKeyCode(detail::ScanCode::PASTE),
  Find = detail::ScanCodeToKeyCode(detail::ScanCode::FIND),
  Mute = detail::ScanCodeToKeyCode(detail::ScanCode::MUTE),
  VolumeUp = detail::ScanCodeToKeyCode(detail::ScanCode::VOLUMEUP),
  VolumeDown = detail::ScanCodeToKeyCode(detail::ScanCode::VOLUMEDOWN),
  KeyPadComma = detail::ScanCodeToKeyCode(detail::ScanCode::KP_COMMA),
  KeyPadEqualsAs400 = detail::ScanCodeToKeyCode(detail::ScanCode::KP_EQUALSAS400),

  AltErase = detail::ScanCodeToKeyCode(detail::ScanCode::ALTERASE),
  SysReq = detail::ScanCodeToKeyCode(detail::ScanCode::SYSREQ),
  Cancel = detail::ScanCodeToKeyCode(detail::ScanCode::CANCEL),
  Clear = detail::ScanCodeToKeyCode(detail::ScanCode::CLEAR),
  Prior = detail::ScanCodeToKeyCode(detail::ScanCode::PRIOR),
  Return2 = detail::ScanCodeToKeyCode(detail::ScanCode::RETURN2),
  Separator = detail::ScanCodeToKeyCode(detail::ScanCode::SEPARATOR),
  Out = detail::ScanCodeToKeyCode(detail::ScanCode::OUT),
  Oper = detail::ScanCodeToKeyCode(detail::ScanCode::OPER),
  ClearAgain = detail::ScanCodeToKeyCode(detail::ScanCode::CLEARAGAIN),
  CrSel = detail::ScanCodeToKeyCode(detail::ScanCode::CRSEL),
  ExSel = detail::ScanCodeToKeyCode(detail::ScanCode::EXSEL),

  KeyPad00 = detail::ScanCodeToKeyCode(detail::ScanCode::KP_00),
  KeyPad000 = detail::ScanCodeToKeyCode(detail::ScanCode::KP_000),
  ThousandSeparator = detail::ScanCodeToKeyCode(detail::ScanCode::THOUSANDSSEPARATOR),
  DecimalSeparator = detail::ScanCodeToKeyCode(detail::ScanCode::DECIMALSEPARATOR),
  CurrencyUnit = detail::ScanCodeToKeyCode(detail::ScanCode::CURRENCYUNIT),
  CurrencySubUnit = detail::ScanCodeToKeyCode(detail::ScanCode::CURRENCYSUBUNIT),
  KeyPadLeftParen = detail::ScanCodeToKeyCode(detail::ScanCode::KP_LEFTPAREN),
  KeyPadRightParen = detail::ScanCodeToKeyCode(detail::ScanCode::KP_RIGHTPAREN),
  KeyPadLeftBrace = detail::ScanCodeToKeyCode(detail::ScanCode::KP_LEFTBRACE),
  KeyPadRightBrace = detail::ScanCodeToKeyCode(detail::ScanCode::KP_RIGHTBRACE),
  KeyPadTab = detail::ScanCodeToKeyCode(detail::ScanCode::KP_TAB),
  KeyPadBackSpace = detail::ScanCodeToKeyCode(detail::ScanCode::KP_BACKSPACE),
  KeyPadA = detail::ScanCodeToKeyCode(detail::ScanCode::KP_A),
  KeyPadB = detail::ScanCodeToKeyCode(detail::ScanCode::KP_B),
  KeyPadC = detail::ScanCodeToKeyCode(detail::ScanCode::KP_C),
  KeyPadD = detail::ScanCodeToKeyCode(detail::ScanCode::KP_D),
  KeyPadE = detail::ScanCodeToKeyCode(detail::ScanCode::KP_E),
  KeyPadF = detail::ScanCodeToKeyCode(detail::ScanCode::KP_F),
  KeyPadXOR = detail::ScanCodeToKeyCode(detail::ScanCode::KP_XOR),
  KeyPadPower = detail::ScanCodeToKeyCode(detail::ScanCode::KP_POWER),
  KeyPadPercent = detail::ScanCodeToKeyCode(detail::ScanCode::KP_PERCENT),
  KeyPadLess = detail::ScanCodeToKeyCode(detail::ScanCode::KP_LESS),
  KeyPadGreater = detail::ScanCodeToKeyCode(detail::ScanCode::KP_GREATER),
  KeyPadAmpersand = detail::ScanCodeToKeyCode(detail::ScanCode::KP_AMPERSAND),
  KeyPadDblAmpersand = detail::ScanCodeToKeyCode(detail::ScanCode::KP_DBLAMPERSAND),
  KeyPadVerticalBar = detail::ScanCodeToKeyCode(detail::ScanCode::KP_VERTICALBAR),
  KeyPadDblVerticalBar = detail::ScanCodeToKeyCode(detail::ScanCode::KP_DBLVERTICALBAR),
  KeyPadColon = detail::ScanCodeToKeyCode(detail::ScanCode::KP_COLON),
  KeyPadHash = detail::ScanCodeToKeyCode(detail::ScanCode::KP_HASH),
  KeyPadSpace = detail::ScanCodeToKeyCode(detail::ScanCode::KP_SPACE),
  KeyPadAt = detail::ScanCodeToKeyCode(detail::ScanCode::KP_AT),
  KeyPadExclam = detail::ScanCodeToKeyCode(detail::ScanCode::KP_EXCLAM),
  KeyPadMemStore = detail::ScanCodeToKeyCode(detail::ScanCode::KP_MEMSTORE),
  KeyPadMemRecal = detail::ScanCodeToKeyCode(detail::ScanCode::KP_MEMRECALL),
  KeyPadMemClear = detail::ScanCodeToKeyCode(detail::ScanCode::KP_MEMCLEAR),
  KeyPadMemAdd = detail::ScanCodeToKeyCode(detail::ScanCode::KP_MEMADD),
  KeyPadMemSubtract = detail::ScanCodeToKeyCode(detail::ScanCode::KP_MEMSUBTRACT),
  KeyPadMemMultiply = detail::ScanCodeToKeyCode(detail::ScanCode::KP_MEMMULTIPLY),
  KeyPadMemDivide = detail::ScanCodeToKeyCode(detail::ScanCode::KP_MEMDIVIDE),
  KeyPadPlusMinus = detail::ScanCodeToKeyCode(detail::ScanCode::KP_PLUSMINUS),
  KeyPadClear = detail::ScanCodeToKeyCode(detail::ScanCode::KP_CLEAR),
  KeyPadClearEntry = detail::ScanCodeToKeyCode(detail::ScanCode::KP_CLEARENTRY),
  KeyPadBinary = detail::ScanCodeToKeyCode(detail::ScanCode::KP_BINARY),
  KeyPadOctal = detail::ScanCodeToKeyCode(detail::ScanCode::KP_OCTAL),
  KeyPadDecimal = detail::ScanCodeToKeyCode(detail::ScanCode::KP_DECIMAL),
  KeyPadHexDecimal = detail::ScanCodeToKeyCode(detail::ScanCode::KP_HEXADECIMAL),

  LCtrl = detail::ScanCodeToKeyCode(detail::ScanCode::LCTRL),
  LShift = detail::ScanCodeToKeyCode(detail::ScanCode::LSHIFT),
  LAlt = detail::ScanCodeToKeyCode(detail::ScanCode::LALT),
  LSuper = detail::ScanCodeToKeyCode(detail::ScanCode::LSuper),
  RCtrl = detail::ScanCodeToKeyCode(detail::ScanCode::RCTRL),
  RShift = detail::ScanCodeToKeyCode(detail::ScanCode::RSHIFT),
  RAlt = detail::ScanCodeToKeyCode(detail::ScanCode::RALT),
  RSuper = detail::ScanCodeToKeyCode(detail::ScanCode::RSuper),

  Mode = detail::ScanCodeToKeyCode(detail::ScanCode::MODE),

  AudioNext = detail::ScanCodeToKeyCode(detail::ScanCode::AUDIONEXT),
  AudioPrev = detail::ScanCodeToKeyCode(detail::ScanCode::AUDIOPREV),
  AudioStop = detail::ScanCodeToKeyCode(detail::ScanCode::AUDIOSTOP),
  AudioPlay = detail::ScanCodeToKeyCode(detail::ScanCode::AUDIOPLAY),
  AudioMute = detail::ScanCodeToKeyCode(detail::ScanCode::AUDIOMUTE),
  MediaSelect = detail::ScanCodeToKeyCode(detail::ScanCode::MEDIASELECT),
  WWW = detail::ScanCodeToKeyCode(detail::ScanCode::WWW),
  Mail = detail::ScanCodeToKeyCode(detail::ScanCode::MAIL),
  Calculator = detail::ScanCodeToKeyCode(detail::ScanCode::CALCULATOR),
  Computer = detail::ScanCodeToKeyCode(detail::ScanCode::COMPUTER),
  AC_Search = detail::ScanCodeToKeyCode(detail::ScanCode::AC_SEARCH),
  AC_Home = detail::ScanCodeToKeyCode(detail::ScanCode::AC_HOME),
  AC_Back = detail::ScanCodeToKeyCode(detail::ScanCode::AC_BACK),
  AC_Forward = detail::ScanCodeToKeyCode(detail::ScanCode::AC_FORWARD),
  AC_Stop = detail::ScanCodeToKeyCode(detail::ScanCode::AC_STOP),
  AC_Refresh = detail::ScanCodeToKeyCode(detail::ScanCode::AC_REFRESH),
  AC_Bookmarks = detail::ScanCodeToKeyCode(detail::ScanCode::AC_BOOKMARKS),

  BrightnessDown = detail::ScanCodeToKeyCode(detail::ScanCode::BRIGHTNESSDOWN),
  BrightnessUp = detail::ScanCodeToKeyCode(detail::ScanCode::BRIGHTNESSUP),
  DisplaySwitch = detail::ScanCodeToKeyCode(detail::ScanCode::DISPLAYSWITCH),
  KBDILLUMTOGGLE = detail::ScanCodeToKeyCode(detail::ScanCode::KBDILLUMTOGGLE),
  KBDILLUMDOWN = detail::ScanCodeToKeyCode(detail::ScanCode::KBDILLUMDOWN),
  KBDILLUMUP = detail::ScanCodeToKeyCode(detail::ScanCode::KBDILLUMUP),
  Eject = detail::ScanCodeToKeyCode(detail::ScanCode::EJECT),
  Sleep = detail::ScanCodeToKeyCode(detail::ScanCode::SLEEP),
  APP1 = detail::ScanCodeToKeyCode(detail::ScanCode::APP1),
  APP2 = detail::ScanCodeToKeyCode(detail::ScanCode::APP2),

  AudioRewind = detail::ScanCodeToKeyCode(detail::ScanCode::AUDIOREWIND),
  AudioFastForward = detail::ScanCodeToKeyCode(detail::ScanCode::AUDIOFASTFORWARD)
};

}// namespace JE