# for full syntax documentation see:  https://lgtm.com/help/lgtm/lgtm.yml-configuration-file
path_classifiers:
  test:
    - "*/fuzz_test/**/*"
    - "*/test/**/*"
extraction:
  cpp:
    prepare:
      packages:
        - g++-10
        - ccache
        - cmake
        - xorg-dev
        - libsdl2-dev
      after_prepare:    # Customizable step used by all languages.
        - export CC=gcc-10
        - export CXX=g++-10
    configure:
      command:
        - mkdir build
        - cmake -D OPT_ENABLE_COVERAGE:BOOL=TRUE -D CMAKE_BUILD_TYPE:STRING=Debug -D ENABLE_DEVELOPER_MODE:BOOL=FALSE  -S . -B build
    index:
      build_command: cmake --build ./build -- -j2
