name: ci
on:
  workflow_dispatch:
  pull_request:
  release:
    types: [published]
  push:
    tags:
    branches:
      - main
      - develop

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  # Conan cache environment variables
  CONAN_SYSREQUIRES_MODE: enabled
  CONAN_USER_HOME: "${{ github.workspace }}/conan-cache"
  CONAN_USER_HOME_SHORT: "${{ github.workspace }}/conan-cache/short"
  # SonarCloud stuff added by me
  SONAR_SCANNER_VERSION: 4.7.0.2747
  SONAR_SERVER_URL: "https://sonarcloud.io"
  BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Directory where build-wrapper output will be placed
  CPPCHECK: /home/cppcheck
  LLVM_VER: 15

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false

      # Recommendations:
      #   * support at least 2 operating systems
      #   * support at least 2 compilers
      #   * make sure all supported configurations for your project are built
      #
      # Disable/enable builds in this list to meet the above recommendations
      # and your own projects needs
      matrix:
        os:
          - ubuntu-20.04
          - macos-11
        compiler:
          - llvm
          - gcc
        generator:
          - "Ninja"
        build_type:
          - Release
          - Debug
        developer_mode:
          - ON
          - OFF
        sonarcloud_build:
          - ON
          - OFF

        exclude:
          # mingw is determined by this author to be too buggy to support
          - os: macos-11
            compiler: gcc

          - os: macos-11
            sonarcloud_build: ON
          - os: windows-2022
            sonarcloud_build: ON


          - os: ubuntu-20.04
            compiler: llvm
            sonarcloud_build: ON
          - os: ubuntu-20.04
            compiler: gcc
            sonarcloud_build: ON
            developer_mode: ON
          - os: ubuntu-20.04
            compiler: gcc
            sonarcloud_build: ON
            developer_mode: OFF
            build_type: Release

          - os: ubuntu-20.04
            developer_mode: ON
            build_type: Release

        include:
          # Add appropriate variables for gcov version required. This will intentionally break
          # if you try to use a compiler that does not have gcov set
          - compiler: gcc
            gcov_executable: gcov
          - compiler: llvm
            gcov_executable: "llvm-cov gcov"

          # Set up preferred package generators, for given build configurations
          - build_type: Release
            developer_mode: OFF
            package_generator: TBZ2

          # AddressSanitizer seems to be broken currently so we disable those builds
          #- os: windows-2022
          #  compiler: msvc
          #  generator: "Visual Studio 17 2022"
          #  build_type: Debug
          #  developer_mode: ON
          #- os: windows-2022
          #  compiler: msvc
          #  generator: "Visual Studio 17 2022"
          #  build_type: Release
          #  developer_mode: ON
          - os: windows-2022
            compiler: msvc
            generator: "Visual Studio 17 2022"
            build_type: Debug
            developer_mode: OFF
          - os: windows-2022
            compiler: msvc
            generator: "Visual Studio 17 2022"
            build_type: Release
            developer_mode: OFF
            package_generator: ZIP


    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.sonar/cache
          key: ${{ runner.os }}-${{ matrix.compiler }}-${{matrix.build_type}}-${{matrix.generator}}-${{matrix.developer_mode}}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.compiler }}-${{matrix.build_type}}-${{matrix.generator}}-${{matrix.developer_mode}}

      - name: Setup Cpp
        if: runner.os != 'Linux' || (runner.os == 'Linux' && matrix.compiler == 'gcc')
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows') }}

          cmake: true
          ninja: true
          conan: false
          vcpkg: false
          ccache: true
          clangtidy: true

          cppcheck: true

          gcovr: 5.0
          opencppcoverage: true

      - name: Setup Cpp - Linux clang
        if: runner.os == 'Linux' && matrix.compiler == 'llvm'
        uses: aminya/setup-cpp@v1
        with:
          cmake: true
          ninja: true
          ccache: true
          gcovr: 5.0
          opencppcoverage: true

      - name: Install valgrind
        if: runner.os == 'Linux'
        run: |
          sudo apt-get -y install valgrind

      - name: Install Linux Packages Needed By SDL
        if: runner.os == 'Linux'
        run: |
          sudo apt-get -y install xorg-dev libsdl2-dev

      - name: Set up JDK 11
        if: matrix.sonarcloud_build == 'ON'
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Download and set up sonar-scanner
        if: matrix.sonarcloud_build == 'ON'
        env:
          SONAR_SCANNER_DOWNLOAD_URL: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${{ env.SONAR_SCANNER_VERSION }}-linux.zip
        run: |
          mkdir -p $HOME/.sonar
          curl -sSLo $HOME/.sonar/sonar-scanner.zip ${{ env.SONAR_SCANNER_DOWNLOAD_URL }} 
          unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
          echo "$HOME/.sonar/sonar-scanner-${{ env.SONAR_SCANNER_VERSION }}-linux/bin" >> $GITHUB_PATH
      - name: Download and set up build-wrapper
        if: matrix.sonarcloud_build == 'ON'
        env:
          BUILD_WRAPPER_DOWNLOAD_URL: ${{ env.SONAR_SERVER_URL }}/static/cpp/build-wrapper-linux-x86.zip
        run: |
          curl -sSLo $HOME/.sonar/build-wrapper-linux-x86.zip ${{ env.BUILD_WRAPPER_DOWNLOAD_URL }}
          unzip -o $HOME/.sonar/build-wrapper-linux-x86.zip -d $HOME/.sonar/
          echo "$HOME/.sonar/build-wrapper-linux-x86" >> $GITHUB_PATH

      - name: Linux - Setup clang-15
        if: runner.os == 'Linux' && matrix.compiler == 'llvm'
        env:
          LLVM_URL: http://apt.llvm.org/focal/
          LLVM_PKG: llvm-toolchain-focal
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install g++-11 gcc-11
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - 2>/dev/null
          sudo add-apt-repository -y "deb ${{ env.LLVM_URL }} ${{ env.LLVM_PKG }} main" && \
              sudo apt-get update -qq 
          export DEBIAN_FRONTEND=noninteractive && \
              sudo apt-get install -y --no-install-recommends \
              clang-${{ env.LLVM_VER }} lldb-${{ env.LLVM_VER }} lld-${{ env.LLVM_VER }} clangd-${{ env.LLVM_VER }} \
              llvm-${{ env.LLVM_VER }}-dev libclang-${{ env.LLVM_VER }}-dev clang-tidy-${{ env.LLVM_VER }}
          sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy $(which clang-tidy-${{ env.LLVM_VER }}) 100 && \
          sudo update-alternatives --install /usr/bin/llvm-cov llvm-cov $(which llvm-cov-${{ env.LLVM_VER }}) 100

      - name: Linux - Setup cppcheck 2.7
        if: runner.os == 'Linux' && matrix.compiler == 'llvm'
        env:
          CPPCHECK_BUILD: ${{ env.CPPCHECK }}/build
          CPPCHECK_SRC: ${{ env.CPPCHECK }}/cppcheck-src
        run: |
          sudo apt-get purge --auto-remove cppcheck
          sudo mkdir -p ${{ env.CPPCHECK_BUILD }}
          sudo apt-get install libxml2-utils && sudo apt-get install libz3-dev libtinyxml2-dev && sudo apt-get install libpcre3-dev
          git clone --branch 2.7 https://github.com/danmar/cppcheck.git ${{ env.CPPCHECK_SRC }}
          CC=clang-${{ env.LLVM_VER }} CXX=clang++-${{ env.LLVM_VER }} cmake -S ${{ env.CPPCHECK_SRC }} -B ${{ env.CPPCHECK_BUILD }} -G "Unix Makefiles" -DHAVE_RULES=On -DBUILD_GUI=Off
          cmake --build ${{ env.CPPCHECK_BUILD }} -j
          sudo cmake --install ${{ env.CPPCHECK_BUILD }}

        # make sure coverage is only enabled for Debug builds, since it sets -O0 to make sure coverage
        # has meaningful results
      - name: Configure CMake - Regular
        if: runner.os != 'Linux' || (runner.os == 'Linux' && matrix.compiler == 'gcc')
        run: |
          cmake -S . -B ./build -G "${{matrix.generator}}" -DCMAKE_BUILD_TYPE:STRING=${{matrix.build_type}} -DENABLE_DEVELOPER_MODE:BOOL=${{matrix.developer_mode}} -DOPT_ENABLE_COVERAGE:BOOL=${{ matrix.build_type == 'Debug' && matrix.developer_mode == 'OFF' }} -DGIT_SHA:STRING=${{ github.sha }} -DOPT_ENABLE_INCLUDE_WHAT_YOU_USE:BOOL=OFF -DENABLE_DEBUG_BREAK:BOOL=OFF
      
      
      - name: Configure CMake - Linux clang
        if: runner.os == 'Linux' && matrix.compiler == 'llvm'
        run: |
          CC=clang-${{ env.LLVM_VER }} CXX=clang++-${{ env.LLVM_VER }} cmake -S . -B ./build -G "${{matrix.generator}}" -DCMAKE_BUILD_TYPE:STRING=${{matrix.build_type}} -DENABLE_DEVELOPER_MODE:BOOL=${{matrix.developer_mode}} -DOPT_ENABLE_COVERAGE:BOOL=${{ matrix.build_type == 'Debug' && matrix.developer_mode == 'OFF' }} -DGIT_SHA:STRING=${{ github.sha }} -DOPT_ENABLE_INCLUDE_WHAT_YOU_USE:BOOL=OFF -DENABLE_DEBUG_BREAK:BOOL=OFF
                    
      - name: Build (Regular)
        if: matrix.sonarcloud_build == 'OFF' || matrix.sonarcloud_build == ''
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: |
          cmake --build ./build --config ${{matrix.build_type}}

      - name: Windows - Install Mesa
        if: runner.os == 'Windows'
        shell: cmd
        working-directory: ./build/${{matrix.build_type}}
        run: |
          curl.exe -L --output mesa.7z --url https://github.com/pal1000/mesa-dist-win/releases/download/20.3.2/mesa3d-20.3.2-release-msvc.7z
          "C:\Program Files\7-Zip\7z.exe" x mesa.7z
          mklink opengl32.dll "x64\opengl32.dll"
          mklink libglapi.dll "x64\libglapi.dll"

      - name: Build (SonarCloud)
        if: matrix.sonarcloud_build == 'ON'
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: |
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} cmake --build ./build --config ${{matrix.build_type}}

      - name: Unix - Test
        if: runner.os != 'Windows'
        env:
          ASAN_OPTIONS: detect_invalid_pointer_pairs=1:strict_string_checks=true:detect_stack_use_after_return=true:check_initialization_order=true:fast_unwind_on_malloc=false:suppressions=${{ github.workspace }}/ASAN.supp
          LSAN_OPTIONS: print_suppressions=false:suppressions=${{ github.workspace }}/LSAN.supp
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ./build
          run: |
            ctest -C ${{matrix.build_type}} --verbose

      - name: Unix - Get Test coverage
        if: runner.os != 'Windows' && matrix.build_type == 'Debug' && matrix.developer_mode == 'OFF'
        working-directory: ./build
        run: |
          gcovr -j ${{env.nproc}} --delete --root ../ --print-summary --xml-pretty --xml coverage.xml --sonarqube coverage_sonarqube.xml . --gcov-executable '${{ matrix.gcov_executable }}'
        
      - name: Linux - Run tests with valgrind
        if: runner.os == 'Linux' && matrix.developer_mode == 'OFF'
        env:
          ASAN_OPTIONS: detect_invalid_pointer_pairs=1:strict_string_checks=true:detect_stack_use_after_return=true:check_initialization_order=true:fast_unwind_on_malloc=false:suppressions=${{ github.workspace }}/ASAN.supp
          LSAN_OPTIONS: print_suppressions=false:suppressions=${{ github.workspace }}/LSAN.supp
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ./build
          run: |
            ctest -C ${{matrix.build_type}} -D NightlyMemCheck --verbose
          
      - name: Windows - Test and coverage
        if: runner.os == 'Windows'
        working-directory: ./build
        run: |
          OpenCppCoverage.exe --export_type cobertura:coverage.xml --cover_children -- ctest -C ${{matrix.build_type}} --verbose

      - name: Run sonar-scanner
        if: matrix.sonarcloud_build == 'ON'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner --define sonar.host.url="${{ env.SONAR_SERVER_URL }}" --define sonar.cfamily.build-wrapper-output="${{ env.BUILD_WRAPPER_OUT_DIR }}"

      - name: CPack
        if: matrix.package_generator != ''
        working-directory: ./build
        run: |
          cpack -C ${{matrix.build_type}} -G ${{matrix.package_generator}}

      - name: Publish Tagged Release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.package_generator != '' }}
        with:
          files: |
            build/*-*${{ matrix.build_type }}*-*.*

      - name: Linux - Upload Valgrind Test logs
        if: (runner.os == 'Linux' && matrix.developer_mode == 'OFF') && always()
        uses: actions/upload-artifact@v3
        with:
          name: Valgrind-Logs-${{ matrix.build_type }}-${{ matrix.compiler }}
          path: ./build/Testing

      - name: Windows - Upload Build folder
        if: (runner.os == 'Windows' && matrix.build_type == 'Debug') && always()
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Build-Debug
          path: ./build

      - name: Publish to codecov
        if: matrix.build_type == 'Debug' && matrix.developer_mode == 'OFF'
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ runner.os }}
          name: ${{ runner.os }}-coverage
          files: ./build/coverage.xml
